name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    
    - name: install readline 
      run: sudo apt install libreadline-dev
       
    - name: make
      run: make release

    - name: change dir 
      run: cd build/release/

    - name: run mujs-plus
      run: ./mujs

    - uses: actions/download-artifact@v4.1.8
